"""
Generate a LaTeX table of the Mermaid diagram frontmatter keys from
frontmatter.schema.json.

Usage:
  cd alo_translator/parsers && ../../.venv/bin/python3 generate_frontmatter_table.py
Outputs:
  table_frontmatter.tex
"""

import json
import re
import sys
from pathlib import Path

SCHEMA_PATH = Path(__file__).parent / "frontmatter.schema.json"
OUT_PATH = Path(__file__).parent / "table_frontmatter.tex"


def tex_escape(s: str) -> str:
    s = s.replace("\\", r"\textbackslash{}")
    s = s.replace("{", r"\{")
    s = s.replace("}", r"\}")
    s = s.replace("_", r"\_")
    s = s.replace("&", r"\&")
    s = s.replace("#", r"\#")
    return s


def type_str(prop: dict) -> str:
    t = prop.get("type", "any")
    if isinstance(t, list):
        return " or ".join(t)
    return t


def write_table(schema: dict, path: Path) -> None:
    lines = [
        r"% Auto-generated by generate_frontmatter_table.py -- do not edit by hand",
        r"% Source: frontmatter.schema.json",
        r"\begin{tabular}{l l p{0.55\linewidth}}",
        r"\hline",
        r"Key & Type & Description \\",
        r"\hline",
    ]
    for key, prop in schema["properties"].items():
        raw_desc = prop.get("paper_description", prop.get("description", ""))
        desc = tex_escape(raw_desc)
        lines.append(f"\\texttt{{{tex_escape(key)}}} & {type_str(prop)} & {desc} \\\\")
    lines += [r"\hline", r"\end{tabular}", ""]
    path.write_text("\n".join(lines))


def main():
    schema = json.loads(SCHEMA_PATH.read_text())
    write_table(schema, OUT_PATH)
    print(f"Wrote {OUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
