---
title: Example 3.1 from Where Responsibility Takes You
description: This is a minimal specification of the corresponding model with all histories except h1 left implicit. Thus, the naming of the other histories might be different than in the book, but the results are the same. Of note is that since we do full responsibility analysis we get results for group {1,2} which has quite a bit of responsibility.
type: DBT
actions:
  1:
    - sd
    - ss
  2:
    - ss
    - ha
opposings:
  sd1:
    - ha2
aliases:
  1: Alice
  2: Beth
  sd: shoots Dan
  ss: stands still
  ha: hits Alice
  q: Dan dies
---
classDiagram
direction BT
  class m {
  }
  m --> m1 : h1({sd1, ss2})
  m1: q
