---
type: DBT
title: Example 3.5 from Where Responsibility Takes You
description: This has 16 histories so is computationally touch for OWL reasoners. We have to explicitly specify all the histories with the target outcome (q). The ~q histories are interpolated.
actions:
  1:
    - sd
    - ss
  2:
    - ss
    - ha
  3:
    - sd
    - ss
  4:
    - rb
    - ss
opposings:
  sd1:
    - ha2
  sd3:
    - rb4
aliases:
  1: Alice
  2: Beth
  3: Carl
  4: Diana
  ha: hits Alice
  q: Dan dies
  rb: run between Carl and Dan
  sd: shoots Dan
  ss: stands still
---
classDiagram
direction BT
  class m {
  }
  m --> m1 : h1({sd1, ss2, sd3, rb4})
  m --> m2 : h2({sd1, ss2, sd3, ss4})
  m --> m3 : h3({sd1, ss2, ss3, ss4})
  m --> m4 : h4({sd1, ss2, ss3, rb4})
  m --> m5 : h5({sd1, ha2, sd3, ss4})
  m --> m6 : h6({ss1, ss2, sd3, ss4})
  m --> m7 : h7({ss1, ha2, sd3, ss4})
  m1: q
  m2: q
  m3: q
  m4: q
  m5: q
  m6: q
  m7: q