---
title: Example 3.7 from Where Responsibility Takes You
description: Structurally, this is similar to 3.1 (only one history, h1, has the successful, non-negated outcome), so we only need specify the h1 successor.
type: DBT
actions:
  1:
    - pd
    - ss
  3:
    - pd
    - ss
aliases:
  1: Alice
  3: Carl
  pd: push Dan
  q: Dan dies
  ss: stands still
---
classDiagram
direction BT
  class m {
  }
  m --> m1 : h1({pd1, pd3})
  m1: q