"""
Sync generated table data into a paper's .tex source, in place.

Two regeneration modes, chosen automatically per marker block:

- Empty block (author has placed bare markers with nothing between them):
  paste the full raw generated table verbatim (same as writing
  table_models.tex/table_translations.tex directly) -- header, column
  spec, caption, everything.
- Non-empty block: row-match by model name (case-insensitive) against
  freshly computed data and swap ONLY that row's data cells in place.
  The model-name cell keeps its paper capitalization ("Isabella" stays
  "Isabella" even though the model file/generator's internal name is
  "isabella"). Header row, \\begin{tabular}{...} column spec, \\caption,
  \\label, and any other row/column formatting the paper has are left
  completely untouched.

Marker format (paired, put directly in the paper .tex):

    % BEGIN GENERATED: table_models

    % END GENERATED: table_models

A row line is any line inside a marker block matching
    ^\\s*([A-Za-z0-9][\\w.]*)\\s*&.*\\\\\\\\\\s*$
i.e. starts with a bare word/model-name token (no backslash, no `%`)
followed by `&`, ends in `\\\\`. Anything else inside the block (header
rows, \\hline, blank lines, \\begin{tabular}{...}, \\caption{...}) is
left alone.

If a row's model name doesn't match any model currently produced by
generate_tables.py's run_model(), this raises -- that's a real
divergence between the paper and the model set, not something to
silently skip.

Usage:
  cd papers/2026Fear && ../../.venv/bin/python3 sync_paper_tables.py <target.tex> [<target.tex> ...]
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from generate_tables import (
    MODELS_DIR,
    PAPER_MODELS,
    run_model,
    tex_escape,
)

ROW_RE = re.compile(r"^\s*([A-Za-z0-9][\w.]*)\s*&.*\\\\\s*$")
MARKER_RE = re.compile(
    r"% BEGIN GENERATED: (?P<name>\S+)\n(?P<body>.*?)% END GENERATED: (?P=name)\n",
    re.DOTALL,
)

TABLE_BUILDERS = {}


def register(name):
    def deco(fn):
        TABLE_BUILDERS[name] = fn
        return fn
    return deco


@register("table_models")
def build_table_models_full(rows) -> str:
    lines = [
        r"\begin{table}[h]",
        r"\centering",
        r"% Auto-generated by generate_tables.py -- do not edit by hand",
        r"\begin{tabular}{l r r r r r r}",
        r"\hline",
        r"Model & Moments & Hist. & Depth & Agents & Actions & Eval pts \\",
        r" & & & & total (max/mom.) & total (max/mom.) & actual (max poss.) \\",
        r"\hline",
    ]
    for r in rows:
        lines.append(table_models_row(r))
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def table_models_row(r) -> str:
    s = r["shape"]
    return (
        f"{tex_escape(r['name'])} & {s['moments']} & {s['histories']} & {s['depth']} & "
        f"{s['agents_total']} ({s['agents_max']}) & {s['actions_total']} ({s['actions_max']}) & "
        f"{s['eval_points_actual']} ({s['eval_points_max']}) \\\\"
    )


@register("table_translations")
def build_table_translations_full(rows) -> str:
    lines = [
        r"\begin{table}[h]",
        r"\centering",
        r"% Auto-generated by generate_tables.py -- do not edit by hand",
        r"\begin{tabular}{l r r r r r r r r r r}",
        r"\hline",
        r"Model & \multicolumn{5}{c}{pyDatalog} & \multicolumn{5}{c}{OWL / Konclude} \\",
        r" & Vocab & Const. & Facts & Rules & Avg.\ time (s) & Vocab & Indiv. & ABox & TBox & Avg.\ time (s) \\",
        r"\hline",
    ]
    for r in rows:
        lines.append(table_translations_row(r))
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def table_translations_row(r) -> str:
    d, o = r["datalog"], r["owl"]
    return (
        f"{tex_escape(r['name'])} & {d['predicates']} & {d['constants']} & {d['facts']} & {d['rules']} & {r['datalog_time']:.3f} & "
        f"{o['predicates']} & {o['individuals']} & {o['abox']} & {o['tbox']} & {r['owl_time']:.3f} \\\\"
    )


ROW_BUILDERS = {
    "table_models": table_models_row,
    "table_translations": table_translations_row,
}


def compute_rows() -> dict:
    mmd_files = [MODELS_DIR / name for name in PAPER_MODELS]
    by_name = {}
    for mmd_path in mmd_files:
        print(f"Analyzing {mmd_path.name}...", file=sys.stderr)
        r = run_model(mmd_path)
        by_name[r["name"].lower()] = r
    return by_name


def sync_block(marker_name: str, body: str, rows_by_name: dict) -> str:
    if marker_name not in TABLE_BUILDERS:
        raise ValueError(f"No table builder registered for marker {marker_name!r} -- add one to sync_paper_tables.py")

    rows = list(rows_by_name.values())

    if body.strip() == "":
        return build_table_models_full(rows) if marker_name == "table_models" else build_table_translations_full(rows)

    row_builder = ROW_BUILDERS[marker_name]

    # Any line whose first cell isn't a known model name is left alone (this
    # is how header rows like "Model & Moments & ..." are distinguished from
    # data rows, without a separate row marker). But that means a row whose
    # model name is stale (renamed/removed/typo'd) would ALSO silently pass
    # through unmatched -- so first collect every candidate "looks like a
    # data row" name (any line matching ROW_RE at all, matched or not) and
    # compare against the known model set explicitly.
    candidate_names = {
        m.group(1) for line in body.splitlines() if (m := ROW_RE.match(line))
    }
    unmatched = {n for n in candidate_names if n.lower() not in rows_by_name}
    known_header_words = {"Model"}
    truly_unmatched = unmatched - known_header_words
    if truly_unmatched:
        raise ValueError(
            f"Row(s) {sorted(truly_unmatched)} in {marker_name} don't match any "
            f"current model ({sorted(rows_by_name)}). Model renamed/removed, or "
            f"a typo? Fix the paper row or the model set. (If this is a new "
            f"header word that happens to look like a data row, add it to "
            f"known_header_words in sync_paper_tables.py.)"
        )

    out_lines = []
    matched_any = False
    for line in body.splitlines(keepends=True):
        m = ROW_RE.match(line)
        if m is None:
            out_lines.append(line)
            continue
        paper_name = m.group(1)
        key = paper_name.lower()
        if key not in rows_by_name:
            out_lines.append(line)
            continue
        matched_any = True
        new_row = row_builder(rows_by_name[key])
        # preserve the paper's own capitalization of the model name
        new_row = new_row.replace(tex_escape(rows_by_name[key]["name"]), paper_name, 1)
        trailing_newline = line[len(line.rstrip("\n")):]
        out_lines.append(new_row + trailing_newline)

    if not matched_any:
        raise ValueError(
            f"No row in {marker_name} matched any current model "
            f"({sorted(rows_by_name)}). Block has content but nothing was "
            f"recognized as a data row -- check row names, or clear the "
            f"block to empty to force a full regenerate."
        )
    return "".join(out_lines)


def sync_file(path: Path, rows_by_name: dict) -> bool:
    text = path.read_text()

    def repl(m):
        name = m.group("name")
        body = m.group("body")
        new_body = sync_block(name, body, rows_by_name)
        return f"% BEGIN GENERATED: {name}\n{new_body}% END GENERATED: {name}\n"

    new_text, n = MARKER_RE.subn(repl, text)
    if n == 0:
        print(f"  (no markers found in {path})", file=sys.stderr)
        return False
    if new_text != text:
        path.write_text(new_text)
        print(f"  updated {n} block(s) in {path}", file=sys.stderr)
        return True
    print(f"  {n} block(s) in {path}, no changes", file=sys.stderr)
    return False


def main():
    targets = [Path(p) for p in sys.argv[1:]]
    if not targets:
        print("Usage: sync_paper_tables.py <target.tex> [<target.tex> ...]", file=sys.stderr)
        sys.exit(1)

    rows_by_name = compute_rows()

    for path in targets:
        print(f"Syncing {path}...", file=sys.stderr)
        sync_file(path, rows_by_name)


if __name__ == "__main__":
    main()
