import streamlit as st

st.set_page_config(page_title="Gen AI Declaration", layout="wide")

st.title("Gen AI Declaration")

st.markdown("""
The code behind the the site as well as the Streamlit was mostly generated by Claude CLI using various versions of Sonnet in a vibe cody with some spec like coding and "code by example" stuff. The design of everything is pretty granularly by me, Bijan Parsia as is the intellectual work of designing the translations, etc. (Boy did things go wrong both design-wise and mapping-wise if I didn't intervene a lot.)

All human facing text was written by hand by me, including the tutorial and help text. I did the coding of the models and creation of tutorial models.

I started by hand crafting some translations into OWL from "Where Responsibility Takes You". I had a translation toolkit for a surface sytax of various modal and deontic logics, Deontickit, and was planning to hack that into work. But it didn't make sense to use formulae to spec a model so I used TOML. At this point, I needed to do some exploring of LMM based coding systems for my software engineering class (gotta teach this stuff) and I though this might be a simple but realistic example. Realistic it proved to be, but not so simple :)

It definitely did not end up the quick hack and have something I can use for a paper project. This was in part because my translations needed some work and OWL reasoners were flakier than I liked. But also because of weird turns and deadends from how I used Claude (and how Claude works).

I'll be writing up some of my experiences in the future. 
""")
